version: "4"
volumes:
  pgadmin:
  postgres:

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: yonatane504@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_POSTGRES_HOST: 172.18.0.2
      PGADMIN_POSTGRES_PORT: 5432
      PGADMIN_POSTGRES_DB: MIYA
      PGADMIN_POSTGRES_USER: Admin
      PGADMIN_POSTGRES_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin

  postgis:
    image: postgis/postgis:latest
    container_name: postgis
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: MIYA
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
